### PR TITLE
Fix UITableViewCell's selected state.

### PR DESCRIPTION
**Pull request by WorldDownTown**
UITableViewCell should be deselected after selected.
Otherwise, if user pops ViewController, cell will be remaining selected.

### CODE REVIEW

**Comment by kishikawakatsumi** [comment]
@WorldDownTown Thanks for pointing out such weird behavior.
But the selection state should be cleared when the previous view will be displayed. It should not be immediately after the cell has been selected.

> It also clears its selection (with or without animation, depending on the request) every time the table view is displayed. The UITableViewController class implements this in the superclass method viewWillAppear:. You can disable this behavior by changing the value in the clearsSelectionOnViewWillAppear property. 
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITableViewController_Class/index.html

`UITableViewController` should implement its behavior by default. But it seems broken when swiping back to the view controller.

So could you change your PR to adjust the standard behavior?

I think the following snippets might work:

```swift
override func viewWillAppear(animated: Bool) {
    super.viewWillAppear(animated)
    if let indexPath = tableView.indexPathForSelectedRow {
        tableView.deselectRowAtIndexPath(indexPath, animated: true)
    }
}
```

**Comment by WorldDownTown** [comment]
@kishikawakatsumi Understood. I'll change the code that way.

**Comment by WorldDownTown** [comment]
@kishikawakatsumi I changed the codes. Please check them.

**Comment by kishikawakatsumi** [comment]
Thank you! :heart_eyes_cat:

**Pull request merged**
